version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
    - .:/usr/src/app
    - ./node_modules:/usr/src/app/node_modules
    - ./node_modules/typeorm:/usr/src/app/node_modules/typeorm
    ports:
    - ${PORT}:${PORT}
    - 9229:9229
    command: npm run start:dev
    env_file:
    - .env
    networks:
    - registration-api
    depends_on:
    - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
    - registration-api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
    - 5432:5432
networks:
  registration-api: